"""In-game drive test: buy each vehicle, run it on a test line, and check that
it moves, how fast it gets, that its sound set loaded, that its horn is
audible, and photograph it moving, close up, from the cab and at night.

    python port.py drive <vehicle> ...       # vehicle config names
    python port.py drive --all
    options: --rebuild          build the test line again (new cached save)
             --save <name>      use your own savegame instead of the test line
             --loco <modId>::/<dir>/<model>.mdl   engine for unpowered cars

The game must be closed; it is started, driven by a --script (see
game_smoke.py and AGENTS.md), and quits by itself.

The test line is made by the script, not shipped: a new game (fixed seed),
the flattest straight north-south strip of the map, and on it a depot, a
station, high-speed electrified track and a second station, plus a line
between the two. The strip is the longest the map has (4.5 km on the default
map: 3.6 km between the stations, where a single 160 km/h car reaches top
speed and a 9-car EMU gets to ~150);
the hand-made save this replaced capped every vehicle at ~100 km/h. The first
run saves it as TESTLINE_SAVE; later runs load that save with the mods under
test (about half a minute less than building it). --rebuild, or a change of
TESTLINE_SAVE, makes a new one.

Per vehicle mod, one test unit: its shortest consist (.mu.lua) if it has
any, so an EMU runs with its cab cars; else its first powered model; else its
first car behind a borrowed locomotive (--loco, or "helper_loco" in
local_settings.json; else whatever powered model loaded first).

Checks and where they come from:
    bought     makeVehicleBuyCmd succeeded at the depot
    maxSpeed   max MOVE_PATH dyn.speed on the line; topSpeed is the lowest
               landVehicle.topSpeed in the unit. "reached" within 3 %;
               "capped" when it levelled off below that for 15 s (wrong
               power, weight or topSpeed); neither = the line ended while it
               was still accelerating, which says nothing is wrong
    soundSet   the model's soundConfig.soundSet.name resolves in soundSetRep
    horn       PC audio output (WASAPI loopback) louder right after
               gui.sound.letVehicleHorn than just before it
    shots      following camera while moving, closer view, cockpit view,
               and from four sides at 23:00 for the lights

Results: logs/drive/<run>/results.json and the screenshots beside it.
"""
import glob
import json
import os
import re
import shutil
import sys
import threading
import time

from . import run as game_run
from . import smoke as game_smoke
from ..common import vehicle_names
from ..paths import LOGS, local_setting

SHOTS = game_smoke.SHOTS

# Bump the version when the layout below changes, so old cached saves are
# not used.
TESTLINE_SAVE = "tf3port_testline_v3"

SCRIPT = r'''
-- generated by port.py drive
local MODS = { %(mods)s }
local USER_SAVE = "%(save)s"
local TESTLINE_SAVE = "%(testline)s"
local REBUILD = %(rebuild)s
local HELPER_LOCO = "%(loco)s"

local LENGTHS = { 6000, 5000, 4500, 4000, 3000 }  -- test strip, longest that fits (m)
local L
local SEG = 100         -- track piece length (m)
local SPEEDUP = 4       -- simulation speed while measuring top speed
local TRACK = "::/infrastructure/track/high_speed/high_speed_catenary.street_template"
local STATION = "::/stations/rail/modular_station/modular_station.con"
local DEPOT = "::/depots/rail/rail_depot.con"

local frame, state, wait = 0, "boot", 0
local depot, line, player, X, newGame
local units, unit = {}, nil
local saveInfo

local function log(...)
	local t = {}
	for i = 1, select("#", ...) do t[#t + 1] = tostring(select(i, ...)) end
	debugPrint("DRIVE: " .. table.concat(t, " "))
end

local function esc(s)
	return tostring(s):gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\n', '\\n')
end
local function emit(t)
	local parts = {}
	for k, val in pairs(t) do
		local vs
		if type(val) == "number" or type(val) == "boolean" then vs = tostring(val)
		elseif type(val) == "table" then
			local a = {}
			for _, x in ipairs(val) do a[#a + 1] = '"' .. esc(x) .. '"' end
			vs = "[" .. table.concat(a, ",") .. "]"
		else vs = '"' .. esc(val) .. '"' end
		parts[#parts + 1] = '"' .. k .. '":' .. vs
	end
	debugPrint("DRIVE_JSON {" .. table.concat(parts, ",") .. "}")
end

local function vec(x, y, z) return api.type.Vec3f.new(x, y, z) end

local function inGame()
	local ok, w = pcall(function() return api.engine.util.getWorld() end)
	return ok and w ~= nil and w >= 0
end

local function quit(why)
	if why then log(why) end
	state = "quit"
	app.quit(true)
end

----------------------------------------------------------------------------
-- the test line

local function h(x, y) return api.engine.terrain.getHeightAt(api.type.Vec2f.new(x, y)) end

-- the flattest straight north-south strip of length len that stays above
-- water (a river across it would need a bridge)
local function findStrip(len)
	local best, bestX
	for x = -6000, 6000, 50 do
		local lo, hi = 1e9, -1e9
		for y = -len / 2 - 100, len / 2 + 100, 50 do
			local z = h(x, y)
			if z < lo then lo = z end
			if z > hi then hi = z end
		end
		if lo > 1 and (not best or hi - lo < best) then best, bestX = hi - lo, x end
	end
	return bestX, best
end

-- the longest strip the map has; on the default map with seed 1, 4.5 km
local function findCorridor()
	for _, len in ipairs(LENGTHS) do
		local x, range = findStrip(len)
		if x then
			L = len
			log("test strip", len, "m at x", x, "height range", string.format("%%.0f", range))
			return x
		end
	end
end

-- Mat4f.new takes columns; a rotation of 0 puts the depot exit and the
-- station track along y
local function at(x, y)
	return api.type.Mat4f.new(
		api.type.Vec4f.new(1, 0, 0, 0), api.type.Vec4f.new(0, 1, 0, 0),
		api.type.Vec4f.new(0, 0, 1, 0), api.type.Vec4f.new(x, y, h(x, y), 1))
end

local function failed(tag, res, ok)
	local es = res and res.resultProposalData and res.resultProposalData.errorState
	if ok and not (es and es.critical) then return false end
	for _, m in ipairs(es and es.messages or {}) do log(tag, "error", m) end
	return true
end

local function moduleEntry(name)
	local d = api.res.moduleRep.get(api.res.moduleRep.find(name))
	local us = d.updateScript
	return { name = name, variant = 0, metadata = d.metadata,
		updateScript = { fileName = us and us.fileName or "", params = us and us.params or {} } }
end

-- An era C through station, one track, 6 x 40 m. A station needs its
-- modules spelt out (without them its updateFn fails on params.modules);
-- these are what the station's createTemplateFn makes for those menu
-- settings: platform in column 0, track in column 1, a main building.
local function stationParams()
	local modules = {}
	local plat = "/stations/rail/modular_station/platform_passenger_era_c.module"
	local track = "/trainstation___/infrastructure/track/standard/standard_catenary.street_template"
	for j = -2, 3 do
		modules[7400000 + 10 * j] = moduleEntry(plat)
		modules[8400000 + 1000 + 10 * j] = moduleEntry(track)
	end
	modules[3400000 + 20] = moduleEntry("/stations/rail/modular_station/main_building_1_era_c.module")
	return { templateIndex = 4, tracks = 0, length = 5, trackType = 2, catenary = 2,
		paramX = 0, paramY = 0, seed = 7, year = 1990, modules = modules }
end

local function conEntity(file, params, transf, name)
	local c = api.type.SimpleProposal.ConstructionEntity.new()
	c.fileName = file
	c.params = params
	c.transf = transf
	c.playerEntity = player
	c.name = name
	return c
end

local function buildConstructions()
	local p = api.type.SimpleProposal.new()
	-- a whole table: assigning p.constructionsToAdd[1] leaves the proposal empty
	p.constructionsToAdd = {
		conEntity(DEPOT, { trackType = 1, catenary = 2, paramX = 0, paramY = 0, seed = 1, year = 1990 },
			at(X, L / 2), "Test depot"),
		conEntity(STATION, stationParams(), at(X, L / 2 - 450), "Test north"),
		conEntity(STATION, stationParams(), at(X, -L / 2 + 200), "Test south"),
	}
	api.cmd.sendCommand(api.cmd.makeWorldBuildProposalCmd(p, nil, true, true), function(res, ok)
		if failed("depot and stations", res, ok) then return quit("could not build the test line") end
		state = "built"; wait = 0
	end)
end

local function nodePos(n)
	return api.engine.getComponent(n, api.type.ComponentType.BASE_NODE).position
end

-- Where new track can join a construction: the far nodes of its frozen
-- edges. Its own (frozen) nodes refuse new track ("cannot build").
local function openEnds(con)
	local c = api.engine.getComponent(con, api.type.ComponentType.CONSTRUCTION)
	local frozen, out = {}, {}
	for _, n in ipairs(c.frozenNodes) do frozen[n] = true end
	for _, e in ipairs(c.frozenEdges) do
		local be = api.engine.getComponent(e, api.type.ComponentType.BASE_EDGE)
		for _, n in ipairs({ be.node0, be.node1 }) do
			if not frozen[n] then out[#out + 1] = n; frozen[n] = true end
		end
	end
	return out
end

local function northmost(nodes, dir)
	local best, by
	for _, n in ipairs(nodes) do
		local p = nodePos(n)
		if math.abs(p.x - X) < 30 and (not best or p.y * dir > by * dir) then best, by = n, p.y end
	end
	return best
end

-- track from node a south to node b: one Hermite curve leaving and
-- arriving straight along -y, cut into ~SEG m pieces
local nextId = -1
local function addTrack(nodes, edges, a, b)
	local tpl = api.res.streetTemplateRep.get(api.res.streetTemplateRep.find(TRACK))
	local pa, pb = nodePos(a), nodePos(b)
	local D = math.abs(pa.y - pb.y)
	local n = math.max(1, math.floor(D / SEG + 0.5))
	local T = { x = 0, y = -D, z = pb.z - pa.z }
	local function mix(c0, c1, c2, c3, k) return c0 * pa[k] + c1 * T[k] + c2 * pb[k] + c3 * T[k] end
	local function pos(t)
		local a0, a1, a2, a3 = 2*t^3 - 3*t^2 + 1, t^3 - 2*t^2 + t, -2*t^3 + 3*t^2, t^3 - t^2
		return vec(mix(a0, a1, a2, a3, "x"), mix(a0, a1, a2, a3, "y"), mix(a0, a1, a2, a3, "z"))
	end
	local function tan(t)
		local a0, a1, a2, a3 = 6*t^2 - 6*t, 3*t^2 - 4*t + 1, -6*t^2 + 6*t, 3*t^2 - 2*t
		return vec(mix(a0, a1, a2, a3, "x") / n, mix(a0, a1, a2, a3, "y") / n, mix(a0, a1, a2, a3, "z") / n)
	end
	local ids = { a }
	for i = 1, n - 1 do
		local nd = api.type.NodeAndEntity.new()
		nd.entity = nextId; nextId = nextId - 1
		nd.comp.position = pos(i / n)
		nodes[#nodes + 1] = nd
		ids[#ids + 1] = nd.entity
	end
	ids[#ids + 1] = b
	for i = 1, n do
		local e = api.type.SegmentAndEntity.new()
		e.entity = nextId; nextId = nextId - 1
		e.comp.node0, e.comp.node1 = ids[i], ids[i + 1]
		e.comp.position0, e.comp.position1 = pos((i - 1) / n), pos(i / n)
		e.comp.tangent0, e.comp.tangent1 = tan((i - 1) / n), tan(i / n)
		e.comp.type = api.type["enum"].BaseEdgeType.NORMAL
		e.comp.typeIndex = 1
		e.type = 1
		e.comp.laneConfigs = tpl.laneConfigs
		e.comp.roadTemplate = TRACK
		e.comp.roadStyle = tpl.streetStyle
		e.comp.roadType = api.type["enum"].RoadType.TRACK
		edges[#edges + 1] = e
	end
	log("track", string.format("%%.0f m", D), n, "pieces")
end

local stations = {}

local function connect()
	api.engine.system.vehicleDepotSystem.forEach(function(e) if not depot then depot = e end end)
	api.engine.forEachEntityWithComponent(function(con)
		local c = api.engine.getComponent(con, api.type.ComponentType.CONSTRUCTION)
		if c and c.fileName == STATION and c.stations and #c.stations > 0 and math.abs(c.transf[13] - X) < 1 then
			stations[#stations + 1] = { con = con, y = c.transf[14],
				group = api.engine.system.stationGroupSystem.getStationGroup(c.stations[1]) }
		end
	end, api.type.ComponentType.CONSTRUCTION)
	table.sort(stations, function(a, b) return a.y > b.y end)
	if not depot or #stations < 2 then return quit("test line: depot or stations missing") end
	local depotCon = api.engine.system.streetConnectorSystem.getConstructionEntityForDepot(depot)
	local north, south = openEnds(stations[1].con), openEnds(stations[2].con)
	local nodes, edges = {}, {}
	addTrack(nodes, edges, northmost(openEnds(depotCon), -1), northmost(north, 1))
	addTrack(nodes, edges, northmost(north, -1), northmost(south, 1))
	local p = api.type.SimpleProposal.new()
	p.streetProposal.nodesToAdd = nodes
	p.streetProposal.edgesToAdd = edges
	api.cmd.sendCommand(api.cmd.makeWorldBuildProposalCmd(p, nil, true, true), function(res, ok)
		if failed("track", res, ok) then return quit("could not build the test line") end
		state = "connected"; wait = 0
	end)
end

local function makeLine()
	local comp = api.type.Line.new()
	local stops = {}
	for i = 1, 2 do
		local st = api.type.Line.Stop.new()
		st.stationGroup = stations[i].group
		st.station = 0
		st.terminal = 0
		stops[i] = st
	end
	comp.stops = stops
	api.cmd.sendCommand(api.cmd.makeLineCreateCmd("Test line", vec(1, 0.5, 0), player, comp), function(res, ok)
		if not ok then return quit("could not create the test line") end
		state = "lined"; wait = 0
	end)
end

-- a mission's reward, the same way: the starting money does not cover the
-- test line and a train
local function money()
	local entry = api.type.JournalEntry.new()
	entry.amount = 500000000
	entry.time = -1
	entry.category.type = api.type.JournalEntry.Type.INCOME
	api.cmd.sendCommand(api.cmd.makeJournalBookAssetCmd(player, entry, vec(0, 0, 0)))
end

local function findSave(name)
	local ns = app.SaveGameNamespace.getSavegame()
	for _, info in ipairs(app.findAllSavegames(ns)) do
		if info.saveName == name or info.saveName == name .. ".sav" then
			local id = api.type.SavegameId.new()
			id.path = info.path
			id.saveGameName = info.saveName
			id.saveGameNamespace = ns
			return id
		end
	end
end

----------------------------------------------------------------------------
-- the test units

local function ours(name)
	for _, mod in ipairs(MODS) do
		if name:sub(1, #mod + 3) == mod .. "::/" then return mod end
	end
end

local function powered(md)
	-- TF3 keeps engines under landVehicle (TF2 had them in railVehicle)
	local e = (md.landVehicle and md.landVehicle.engines)
		or (md.railVehicle and md.railVehicle.engines)
	return e ~= nil and #e > 0
end

local function soundOk(md)
	local sc = md.soundConfig and md.soundConfig.soundSet
	local n = sc and sc.name
	if not n or n == "" then return "none" end
	local ok, id = pcall(api.res.soundSetRep.find, n)
	return (ok and id and id >= 0) and "ok" or ("missing " .. n)
end

local function topSpeed(ids)
	local top
	for _, id in ipairs(ids) do
		local m = id >= 0 and api.res.modelRep.get(id)
		local s = m and m.metadata.landVehicle and m.metadata.landVehicle.topSpeed
		if s and s > 0 and (not top or s < top) then top = s end
	end
	return top or 0
end

-- consist vehicle names are relative to the .mu file's folder
local function consists(mod)
	local out = {}
	for id, name in pairs(api.res.multipleUnitRep.getAll()) do
		if ours(name) == mod then
			local mu = api.res.multipleUnitRep.get(id)
			local dir = name:match("^(.*/)") or (mod .. "::/")
			local ids, rev, ok = {}, {}, true
			for i, v in ipairs(mu.vehicles) do
				local mid = api.res.modelRep.find(v.name)
				if not mid or mid < 0 then mid = api.res.modelRep.find(dir .. v.name) end
				if not mid or mid < 0 then ok = false break end
				ids[i], rev[i] = mid, not v.forward
			end
			if ok and #ids > 0 then out[#out + 1] = { file = name, ids = ids, reversed = rev } end
		end
	end
	table.sort(out, function(a, b)
		if #a.ids ~= #b.ids then return #a.ids < #b.ids end
		return a.file < b.file
	end)
	return out
end

local function plan()
	local byMod, loco = {}, nil
	for id, name in pairs(api.res.modelRep.getAll()) do
		if name:sub(-4) == ".mdl" then
			local mod = ours(name)
			local m = mod and api.res.modelRep.get(id)
			local md = m and m.metadata
			if md and md.railVehicle then
				byMod[mod] = byMod[mod] or {}
				table.insert(byMod[mod], { id = id, file = name, powered = powered(md), sound = soundOk(md) })
				if name == HELPER_LOCO then loco = id end
			end
		end
	end
	for _, mod in ipairs(MODS) do
		local list = byMod[mod] or {}
		table.sort(list, function(a, b) return a.file < b.file end)
		for _, l in ipairs(list) do
			if l.powered and not loco then loco = l.id end
		end
		local mus = consists(mod)
		local pick
		for _, l in ipairs(list) do if l.powered then pick = l break end end
		if mus[1] then
			local mu = mus[1]
			local first = api.res.modelRep.get(mu.ids[1])
			units[#units + 1] = { mod = mod, file = mu.file, ids = mu.ids, reversed = mu.reversed,
				cars = #mu.ids, sound = soundOk(first.metadata) }
		elseif pick then
			units[#units + 1] = { mod = mod, file = pick.file, sound = pick.sound, ids = { pick.id }, cars = 1 }
		elseif list[1] then
			units[#units + 1] = { mod = mod, file = list[1].file, sound = list[1].sound,
				ids = { -1, list[1].id }, cars = 1, towed = true }
		else
			units[#units + 1] = { mod = mod, file = "", error = "no rail vehicles loaded" }
		end
	end
	for _, u in ipairs(units) do
		if u.towed then u.ids[1] = loco or -1 end
	end
	log("units", #units, "helper loco", tostring(loco))
end

local function shot(tag)
	api.gui.camera.takeScreenshot(1)
	log("SHOT", unit.file, tag)
	unit.shots = unit.shots or {}
	unit.shots[#unit.shots + 1] = tag
end

local function buy()
	unit = table.remove(units, 1)
	if not unit then return false end
	if unit.error or unit.ids[1] == -1 then
		unit.error = unit.error or "no locomotive to tow it"
		unit.ids, unit.reversed = nil, nil
		emit(unit)
		state = "next"
		return true
	end
	local tvc = api.type.TransportVehicleConfig.new()
	local parts, groups = {}, {}
	for i, id in ipairs(unit.ids) do
		local p = api.type.TransportVehiclePart.new()
		local vp = api.type.VehiclePart.new()
		vp.modelId = id
		vp.reversed = unit.reversed and unit.reversed[i] or false
		-- one entry per compartment, -1 = automatic; an empty list trips an
		-- assertion in UpdateConfigFromModelIds and kills the game
		local m = api.res.modelRep.get(id)
		local tv = m and m.metadata and m.metadata.transportVehicle
		local comps = tv and (tv.compartments or tv.compartmentsList) or {}
		-- and autoLoadConfig on the part, the same length (another assertion)
		local lc, auto = {}, {}
		for c = 1, #comps do
			local l = api.type.LoadConfig.new()
			l.loadConfigIndex = 0
			lc[c] = l
			auto[c] = true
		end
		vp.compartment2loadConfig = lc
		p.autoLoadConfig = auto
		p.part = vp
		parts[i] = p
		groups[i] = 1
	end
	tvc.vehicles = parts
	tvc.vehicleGroups = groups
	unit.topSpeed = topSpeed(unit.ids)
	state = "buying"
	api.cmd.sendCommand(api.cmd.makeVehicleBuyCmd(player, depot, tvc), function(res, ok)
		if ok and res and res.resultVehicleEntity and res.resultVehicleEntity >= 0 then
			unit.vehicle = res.resultVehicleEntity
			unit.bought = true
			api.cmd.sendCommand(api.cmd.makeVehicleSetLineCmd(unit.vehicle, line, 0))
			api.gui.camera.followEntity(unit.vehicle, true)
			unit.maxSpeed = 0
			unit.stops = 0
			api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(SPEEDUP))
			wait = 0
			state = "approach"
		else
			unit.bought = false
			unit.error = "buy failed"
			unit.ids, unit.reversed = nil, nil
			emit(unit)
			state = "next"
		end
	end)
	return true
end

local function finishUnit()
	api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(1))
	if unit.vehicle then
		api.cmd.sendCommand(api.cmd.makeVehicleSellCmd({ unit.vehicle }))
	end
	unit.ids, unit.reversed, unit.riseSpeed, unit.riseAt, unit.atTerminal = nil, nil, nil, nil, nil
	if unit.topSpeed and unit.topSpeed > 0 and unit.maxSpeed then
		unit.reached = unit.maxSpeed >= 0.97 * unit.topSpeed
	end
	emit(unit)
	api.cmd.sendCommand(api.cmd.makeGameSetTimeOfDayCmd(12 * 3600))
	state = "next"
end

local okE, AT_TERMINAL = pcall(function() return api.type.enum.TransportVehicleState.AT_TERMINAL end)
if not okE or AT_TERMINAL == nil then AT_TERMINAL = 2 end

local function vehicleNow()
	local ok, mp = pcall(api.engine.getComponent, unit.vehicle, api.type.ComponentType.MOVE_PATH)
	local sp = ok and mp and mp.dyn and mp.dyn.speed or 0
	local ok2, tv = pcall(api.engine.getComponent, unit.vehicle, api.type.ComponentType.TRANSPORT_VEHICLE)
	return sp, ok2 and tv and tv.state
end

local function cam(dist, pitch, angle)
	-- the follow camera keeps tracking; only distance, angle and pitch change
	local cd = api.gui.camera.getCameraData()
	api.gui.camera.setCameraData(api.type.Vec5f.new(cd[1], cd[2], dist, angle or cd[4], pitch))
end

----------------------------------------------------------------------------

local step

function data()
	return {
		-- an error inside update would otherwise repeat every frame forever:
		-- record it against the current unit and move on, or quit
		update = function()
			if state == "quit" then return end
			local ok, err = pcall(step)
			if not ok then
				if type(err) == "table" then
					local parts = {}
					for k, v in pairs(err) do parts[#parts + 1] = tostring(k) .. "=" .. tostring(v) end
					err = "{" .. table.concat(parts, "; ") .. "}"
				end
				log("ERROR", tostring(err))
				if unit and unit.file then
					unit.error = tostring(err)
					local ok2 = pcall(finishUnit)
					if not ok2 then state = "next" end
				else
					quit()
				end
			end
		end,
		handleEvent = function() end,
	}
end

local function startNewGame()
	local p = api.type.StartGameParams.new()
	p.mods = MODS
	-- fixed, so every run gets the same map and the same strip
	p.seed = "1"
	local ok, err = pcall(app.startGame, p)
	log("new game for the test line", tostring(ok), tostring(err))
	newGame = true
	state = "loading"; wait = 0
end

local function onWorldReady()
	player = api.engine.util.getPlayer()
	api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(1))
	api.cmd.sendCommand(api.cmd.makeGameSetTimeOfDayCmd(12 * 3600))
	money()
	if newGame then
		X = findCorridor()
		if not X then return quit("no strip of land long enough for the test line") end
		buildConstructions()
		state = "building"; wait = 0
		return
	end
	-- a loaded save (the cached test line or the user's): first depot, first line
	-- (forEachEntityWithComponent refuses these, "Cannot loop over this component")
	api.engine.system.vehicleDepotSystem.forEach(function(e) if not depot then depot = e end end)
	local lines = api.engine.system.lineSystem.getLines()
	line = lines and lines[1]
	log("depot", tostring(depot), "line", tostring(line))
	if not depot or not line then return quit("need a depot and a line in the save") end
	local okp, errp = pcall(plan)
	if not okp then log("plan failed", tostring(errp)) end
	state = "next"
end

step = function()
	frame = frame + 1
	wait = wait + 1
	if state == "boot" and frame > 60 then
		local name = USER_SAVE ~= "" and USER_SAVE or TESTLINE_SAVE
		local id = findSave(name)
		if USER_SAVE ~= "" and not id then return quit("save not found: " .. USER_SAVE) end
		if not id or (USER_SAVE == "" and REBUILD) then return startNewGame() end
		if USER_SAVE ~= "" then
			log("loading", name)
			app.loadGame(id, false)
			state = "loading"; wait = 0
		else
			-- the cached test line, with this run's mods instead of the ones it was saved with
			saveInfo = { id = id, async = app.getSavegameInfo(id) }
			state = "saveinfo"; wait = 0
		end
	elseif state == "saveinfo" then
		if saveInfo.async:isCompleted() then
			local d = saveInfo.async:get()
			if not d or (d.errorMsg and d.errorMsg ~= "") then
				log("cached test line unreadable", d and d.errorMsg or "")
				return startNewGame()
			end
			-- a list of Mod.ModId, not of strings (a string list is thrown back
			-- as the error)
			local info = d.info
			local ids = {}
			for i, m in ipairs(MODS) do
				local mid = (api.type.Mod and api.type.Mod.ModId or api.type.ModId).new()
				mid.name = m
				ids[i] = mid
			end
			info.mods = ids
			log("loading", TESTLINE_SAVE)
			app.loadGame(saveInfo.id, false, info)
			state = "loading"; wait = 0
		elseif wait > 600 then
			startNewGame()
		end
	elseif state == "loading" then
		if app.isWaitForStartReadyGame and app.isWaitForStartReadyGame() then
			pcall(app.startReadyGame)
		end
		if inGame() and wait > 120 then
			onWorldReady()
		elseif wait > 60 * 240 then
			quit("the game never got going")
		end
	elseif state == "built" and wait == 10 then
		connect()
		state = "building"; wait = 0
	elseif state == "connected" and wait == 10 then
		makeLine()
		state = "building"; wait = 0
	elseif state == "lined" and wait == 10 then
		local lines = api.engine.system.lineSystem.getLines()
		line = lines[#lines]
		log("test line built: depot", tostring(depot), "line", tostring(line))
		state = "saving"; wait = 0
		app.saveGame(TESTLINE_SAVE, function() log("test line saved as", TESTLINE_SAVE) end, false, true)
	elseif state == "saving" and wait == 120 then
		local okp, errp = pcall(plan)
		if not okp then log("plan failed", tostring(errp)) end
		state = "next"
	elseif state == "building" and wait > 900 then
		quit("timed out building the test line")
	elseif state == "next" then
		if not buy() then quit("done") end
	elseif state == "approach" then
		-- sped up: out of the depot, into the first station and out again.
		-- Shots in the depot showed only the shed, and the cockpit view
		-- did not take there
		local s, st = vehicleNow()
		if s > unit.maxSpeed then unit.maxSpeed = s end
		local terminal = st == AT_TERMINAL
		if terminal and not unit.atTerminal then unit.stops = unit.stops + 1 end
		unit.atTerminal = terminal
		if unit.stops >= 1 and not terminal and s > 3 then
			api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(1))
			state = "shots"; wait = 0
		elseif wait > 60 * 90 then
			unit.error = "never left the first station"
			api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(1))
			state = "shots"; wait = 0
		end
	elseif state == "shots" then
		local s = vehicleNow()
		if s > unit.maxSpeed then unit.maxSpeed = s end
		local cars = unit.cars or 1
		if wait == 30 then cam(30 + 6 * cars, 0.30) end
		if wait == 90 then shot("moving") end
		if wait == 120 then cam(16 + 4 * cars, 0.12) end
		if wait == 180 then shot("close") end
		-- the driver's seat: a misplaced seat gives a cockpit view from
		-- outside the cab or inside the bodywork. The horn goes here too: the
		-- sound is positional, and from the cab the listener is next to it
		-- (from beside a long consist it was lost); three blasts give the
		-- loopback analysis something unmistakable
		if wait == 210 then
			local ok, err = pcall(api.gui.camera.enterFollowCameraCockpit, unit.vehicle)
			log("cockpit", tostring(ok), tostring(err))
		end
		if wait == 270 or wait == 330 or wait == 390 then
			api.gui.sound.letVehicleHorn(unit.vehicle)
			log("HORN", unit.file)
		end
		if wait == 450 then shot("cockpit") end
		if wait == 480 then
			pcall(api.gui.camera.leaveFollowCameraCockpit)
			api.gui.camera.followEntity(unit.vehicle, true)
			api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(SPEEDUP))
			state = "measure"; wait = 0
		end
	elseif state == "measure" then
		-- sped up: until top speed, or the train is in the far station
		local s, st = vehicleNow()
		if s > unit.maxSpeed then unit.maxSpeed = s end
		local terminal = st == AT_TERMINAL
		if terminal and not unit.atTerminal then unit.stops = unit.stops + 1 end
		unit.atTerminal = terminal
		local top = unit.topSpeed or 0
		-- levelled off below its top speed (cruising, not braking for the
		-- station): power, weight or topSpeed came out wrong. Still climbing
		-- when the line ends is only a short line
		if s > (unit.riseSpeed or 0) + 0.05 then unit.riseSpeed, unit.riseAt = s, wait end
		local flat = unit.riseAt and wait - unit.riseAt > 15 * 60 / SPEEDUP and s >= 0.98 * unit.maxSpeed
		if flat and top > 0 and unit.maxSpeed < 0.97 * top and unit.maxSpeed > 1 then unit.capped = true end
		if (top > 0 and unit.maxSpeed >= 0.995 * top and wait > 60) or unit.capped or unit.stops >= 2 or wait > 60 * 120 then
			log("measured", unit.file, string.format("%%.1f of %%.1f m/s", unit.maxSpeed, top), "stops", unit.stops)
			api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(1))
			api.cmd.sendCommand(api.cmd.makeGameSetTimeOfDayCmd(23 * 3600))
			state = "night"; wait = 0
		end
	elseif state == "night" then
		-- lamps face along the track and barely show side-on, so go round
		-- the train: four views 90 degrees apart, one of them is the front
		for k = 0, 3 do
			local t0 = 60 + k * 45
			if wait == t0 then
				local cd = api.gui.camera.getCameraData()
				if k == 0 then unit.camAngle = cd[4] end
				cam(24 + 4 * (unit.cars or 1), 0.08, unit.camAngle + k * math.pi / 2)
			elseif wait == t0 + 30 then
				shot("night" .. k)
			end
		end
		if wait >= 60 + 4 * 45 + 10 then finishUnit() end
	end
end
'''


class Recorder(threading.Thread):
    """Records the default speaker's output (loopback) as RMS per 0.1 s."""

    def __init__(self):
        super().__init__(daemon=True)
        self.rms, self.t0, self.stop = [], None, False

    def run(self):
        import warnings
        import numpy as np
        import soundcard as sc
        # "data discontinuity in recording" every few blocks while the game
        # loads; harmless for an RMS level
        warnings.filterwarnings("ignore", category=sc.SoundcardRuntimeWarning)
        mic = sc.get_microphone(id=str(sc.default_speaker().name), include_loopback=True)
        with mic.recorder(samplerate=48000) as rec:
            self.t0 = time.time()
            while not self.stop:
                d = rec.record(numframes=4800)
                self.rms.append((time.time(), float(np.sqrt((d ** 2).mean()))))

    def level(self, a, b, how=max):
        xs = sorted(r for t, r in self.rms if a <= t < b)
        if not xs:
            return 0.0
        return xs[len(xs) // 2] if how == "median" else how(xs)


def log_times(path, tag):
    """Wall-clock times of DRIVE lines with `tag`, from the game log."""
    import calendar
    out = []
    for l in open(path, encoding="utf-8", errors="replace"):
        if tag in l:
            m = re.match(r"\[(\d+)-(\d+)-(\d+) (\d+):(\d+):(\d+)Z", re.sub(r"\x1b\[[0-9;]*m", "", l))
            if m:
                t = calendar.timegm(tuple(int(x) for x in m.groups()) + (0, 0, 0))
                out.append((t, l.split(tag, 1)[1].strip()))
    return out


def drive_sheet(outdir, w=360):
    """One row per unit, one column per shot; night shots brightened 2.5x."""
    from PIL import Image, ImageDraw, ImageEnhance
    shots = sorted(f for f in os.listdir(outdir) if re.match(r"\d{3}_.*\.png$", f))
    rows = {}
    for f in shots:
        m = re.match(r"\d{3}_(.*)_([a-z]+\d?)\.png$", f)
        if m:
            rows.setdefault(m.group(1), []).append((m.group(2), f))
    if not rows:
        return None
    h = int(w * 9 / 16)
    cols = max(len(v) for v in rows.values())
    sheet = Image.new("RGB", (cols * w, len(rows) * (h + 20)), (24, 24, 24))
    d = ImageDraw.Draw(sheet)
    for r, (unit, items) in enumerate(rows.items()):
        y = r * (h + 20)
        d.text((4, y + 4), unit, fill=(255, 255, 255))
        for c, (tag, f) in enumerate(items):
            im = Image.open(os.path.join(outdir, f)).convert("RGB").resize((w, h))
            if tag.startswith("night"):
                im = ImageEnhance.Brightness(im).enhance(2.5)
            sheet.paste(im, (c * w, y + 20))
            d.text((c * w + 4, y + 22), tag, fill=(255, 255, 0))
    path = os.path.join(outdir, "sheet.png")
    sheet.save(path)
    return path


def main():
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    args = sys.argv[1:]
    opts = {"--save": "", "--loco": local_setting("helper_loco", "")}
    for k in opts:
        if k in args:
            i = args.index(k)
            opts[k] = args[i + 1]
            args = args[:i] + args[i + 2:]
    rebuild = "--rebuild" in args
    args = [a for a in args if a != "--rebuild"]
    if not args:
        sys.exit(__doc__)
    names = vehicle_names() if args == ["--all"] else args
    mods = game_smoke.vehicles(names)
    d = game_smoke.ensure_tools_mod()
    open(os.path.join(d, "content", "drive.lua"), "w", encoding="utf-8").write(SCRIPT % {
        "mods": ", ".join('"%s"' % m for m in mods),
        "save": opts["--save"], "testline": TESTLINE_SAVE,
        "rebuild": "true" if rebuild else "false", "loco": opts["--loco"]})

    run = time.strftime("%Y%m%d_%H%M%S")
    outdir = os.path.join(LOGS, "drive", run)
    os.makedirs(outdir, exist_ok=True)
    before = set(glob.glob(os.path.join(SHOTS, "*")))
    started = time.time()
    rec = Recorder()
    rec.start()
    code, killed, secs = game_run.run(["--script", "%s::/drive.lua" % game_smoke.TOOLS_MOD],
                                      timeout=300 + 120 * len(mods),
                                      log=os.path.join(outdir, "stdout.txt"))
    rec.stop = True
    print("game exit=%s killed=%s after %.0fs" % (code, killed, secs))
    glog = os.path.join(outdir, "game_log.txt")
    shutil.copy2(game_run.GAME_LOG, glog)
    for _, msg in log_times(glog, "DRIVE: "):
        if msg.startswith(("new game", "loading", "test line", "test strip", "track ",
                           "measured", "could", "no strip", "need ", "save not", "timed",
                           "the game", "ERROR", "cached")):
            print("  " + msg)

    results = []
    for l in open(glog, encoding="utf-8", errors="replace"):
        if "DRIVE_JSON " in l:
            try:
                results.append(json.loads(l.split("DRIVE_JSON ", 1)[1].strip()))
            except ValueError:
                pass
    horns = log_times(glog, "DRIVE: HORN")
    for r in results:
        times = [t for t, f in horns if f == r.get("file")]
        if not times:
            continue
        t = times[0]
        # the log has 1 s resolution: baseline well before, blasts within 4 s
        base = rec.level(t - 5.0, t - 1.0, "median")
        peak = rec.level(t, t + 4.0)
        r["hornLevel"] = [round(base, 4), round(peak, 4)]
        r["horn"] = "heard" if peak > max(1.5 * base, base + 0.004) else "not heard"
    shots = sorted((f for f in glob.glob(os.path.join(SHOTS, "*"))
                    if f not in before and os.path.getmtime(f) >= started - 1),
                   key=os.path.getmtime)
    tags = [(f, tag) for _, x in log_times(glog, "DRIVE: SHOT") for f, tag in [x.rsplit(" ", 1)]]
    for i, (src, (f, tag)) in enumerate(zip(shots, tags)):
        stem = re.sub(r"[^a-z0-9_.-]+", "_", f.split("::/")[-1].lower())
        dst = os.path.join(outdir, "%03d_%s_%s%s" % (i, stem, tag, os.path.splitext(src)[1]))
        shutil.move(src, dst)
    json.dump(results, open(os.path.join(outdir, "results.json"), "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)
    print("%d units -> %s  (overview: %s)" % (len(results), outdir, drive_sheet(outdir)))
    for r in results:
        top = r.get("topSpeed") or 0
        verdict = ("reached" if r.get("reached") else "CAPPED" if r.get("capped")
                   else "climbing" if top else "")
        speed = "%5.1f/%5.1f %-8s" % (r.get("maxSpeed", 0) or 0, top, verdict)
        print("  %-44s cars=%-2s bought=%-5s speed=%s sound=%-8s horn=%-9s %s" % (
            r.get("file", r.get("mod")), r.get("cars", "-"), r.get("bought"), speed,
            str(r.get("sound"))[:8], r.get("horn", "-"), r.get("error", "")))


if __name__ == "__main__":
    main()
