"""In-game smoke test: start a test game with the ported mods, photograph
every vehicle model, record its name, quit. No hands needed.

    python port.py smoke <vehicle> ...       # vehicle config names
    python port.py smoke --all

How it works: TransportFever3.exe takes `--script <modId>::/<file>`; the
file's data() returns { update = fn, handleEvent = fn } and update runs every
frame with the `app` and `api` modules available (see app.d.tl and
api/*.d.tl in the install's api/tealdef). This writes such a script into a
helper staging mod (zz_port_tools), runs the game through it, and collects:

    logs/smoke/<run>/models.json   per model: file, name, rail, year, shot
    logs/smoke/<run>/<n>_<model>.png  a screenshot of each model

The script starts a game with app.startGame (mods listed in StartGameParams),
pauses it at noon, and for each model creates a custom entity
(cmd.makeCustomEntityCreateCmd), puts it on the ground beside the map
centre, points the camera at it and takes a screenshot.
"""
import glob
import json
import os
import re
import shutil
import sys
import time

from . import run as game_run
from ..common import vehicle_path, vehicle_names
from ..paths import GAME_LOG, LOGS, SCREENSHOTS_ROOT as SHOTS, STAGING

TOOLS_MOD = "zz_port_tools"

SCRIPT = r'''
-- generated by port.py smoke
local MODS = { %(mods)s }
local SETTLE = %(settle)d   -- frames to let textures stream in before a shot
local CAM_DIST, CAM_ANGLE, CAM_PITCH = %(dist)s, %(angle)s, %(pitch)s

local frame, state, wait = 0, "boot", 0
local queue, current, results = {}, nil, {}
local origin

local function log(...) debugPrint("SMOKE: " .. table.concat({...}, " ")) end
local function inGame()
	local ok, w = pcall(function() return api.engine.util.getWorld() end)
	return ok and w ~= nil and w >= 0
end

local function ours(name)
	for _, mod in ipairs(MODS) do
		if name:sub(1, #mod + 3) == mod .. "::/" then return mod end
	end
end

local function collect()
	for id, name in pairs(api.res.modelRep.getAll()) do
		if ours(name) and name:sub(-4) == ".mdl" then
			local m = api.res.modelRep.get(id)
			local md = m and m.metadata or {}
			if md.railVehicle or md.transportVehicle then
				local bb = m.boundingInfo
				queue[#queue + 1] = { id = id, file = name,
					name = md.description and md.description.name or "",
					year = md.availability and md.availability.yearFrom or -1,
					length = bb and (bb.bbMax.x - bb.bbMin.x) or 20 }
			end
		end
	end
	table.sort(queue, function(a, b) return a.file < b.file end)
	log("models", #queue)
end

local function place(entity)
	local m = api.type.Mat4f.new(
		api.type.Vec4f.new(1, 0, 0, 0), api.type.Vec4f.new(0, 1, 0, 0),
		api.type.Vec4f.new(0, 0, 1, 0),
		api.type.Vec4f.new(origin.x, origin.y, origin.z, 1))
	api.cmd.sendCommand(api.cmd.makeCustomEntityUpdateTransformationCmd(entity, m))
end

local function nextModel()
	current = table.remove(queue, 1)
	if not current then return false end
	state = "creating"
	api.cmd.sendCommand(api.cmd.makeCustomEntityCreateCmd(current.id), function(res, ok)
		if ok and res and res.resultEntity then
			current.entity = res.resultEntity
			place(res.resultEntity)
			-- colour-blend (CBLEND) bodies take the vehicle colour and a bare
			-- entity has none, so they render black. It cannot be given one
			-- either: makeEntitySetColorCmd on a custom entity trips an
			-- assertion (no Color component) and kills the game.
			api.gui.camera.focusPosition(api.type.Vec3f.new(origin.x, origin.y, origin.z + 2), 32)
			wait = 0
			state = "settling"
		else
			log("create failed", current.file)
			current.error = "create failed"
			results[#results + 1] = current
			state = "next"
		end
	end)
	return true
end

local function esc(s)
	return tostring(s):gsub('\\', '\\\\'):gsub('"', '\\"'):gsub('\n', '\\n')
end

local function finish()
	-- one JSON object per line in the game log; game_smoke.py reads them back
	for _, r in ipairs(results) do
		debugPrint(string.format('SMOKE_JSON {"file":"%%s","name":"%%s","year":%%d,"shot":%%s%%s}',
			esc(r.file), esc(r.name), r.year or -1, tostring(r.shot == true),
			r.error and (',"error":"' .. esc(r.error) .. '"') or ""))
	end
	log("done", #results)
	state = "quit"
	app.quit(true)
end

function data()
	return {
		update = function()
			frame = frame + 1
			if state == "boot" and frame > 60 then
				local p = api.type.StartGameParams.new()
				p.mods = MODS
				local ok, err = pcall(app.startGame, p)
				log("startGame", tostring(ok), tostring(err))
				state = "loading"
			elseif state == "loading" and inGame() then
				wait = wait + 1
				if wait > 120 then
					api.cmd.sendCommand(api.cmd.makeGameSetSpeedCmd(0))
					api.cmd.sendCommand(api.cmd.makeGameSetTimeOfDayCmd(12 * 3600))
					local c = api.type.Vec2f.new(0, 0)
					origin = { x = 0, y = 0, z = api.engine.terrain.getHeightAt(c) }
					local ok, err = pcall(collect)
					if not ok then log("collect failed", tostring(err)) end
					state = "next"
				end
			elseif state == "next" then
				if not nextModel() then finish() end
			elseif state == "settling" then
				wait = wait + 1
				if wait == 2 then
					-- side-on, low, framed to the model's length
					local cd = api.gui.camera.getCameraData()
					local len = current.length or 20
					log("camera", cd[1], cd[2], cd[3], cd[4], cd[5])
					api.gui.camera.setCameraData(api.type.Vec5f.new(
						origin.x, origin.y, len * CAM_DIST, CAM_ANGLE, CAM_PITCH))
				end
				if wait == SETTLE then
					api.gui.camera.takeScreenshot(1)
				elseif wait == SETTLE + 30 then
					log("shot", current.file)
					current.shot = true
					results[#results + 1] = current
					api.cmd.sendCommand(api.cmd.makeCustomEntityDestroyCmd(current.entity))
					current.entity = nil
					state = "next"
				end
			end
		end,
		handleEvent = function() end,
	}
end
'''


def vehicles(names):
    out = []
    for n in names:
        cfg = json.load(open(vehicle_path(n),
                             encoding="utf-8"))
        out.append(cfg["modId"])
    return out


def ensure_tools_mod():
    d = os.path.join(STAGING, TOOLS_MOD)
    os.makedirs(os.path.join(d, "content"), exist_ok=True)
    os.makedirs(os.path.join(d, "_metadata"), exist_ok=True)
    if not os.path.exists(os.path.join(d, "mod.json")):
        json.dump({"cosmetic": True, "dependencies": None, "incompatibilities": None,
                   "modId": TOOLS_MOD, "options": None, "params": None,
                   "postRunScript": {"fileName": ""}, "preRunScript": {"fileName": ""},
                   "revision": 1, "runScript": {"fileName": ""},
                   "severityAdd": "None", "severityRemove": "None"},
                  open(os.path.join(d, "mod.json"), "w"), indent=4)
        json.dump({"authors": [], "name": "Port tools (test scripts)", "tags": [],
                   "description": "Scripts for port.py smoke. Not a gameplay mod.",
                   "url": ""},
                  open(os.path.join(d, "_metadata", "modinfo.json"), "w"), indent=4)
    return d




def contact_sheets(outdir, models, cols=3, rows=4, w=560):
    """Tile the shots, centre-cropped and labelled, 12 to a sheet."""
    from PIL import Image, ImageDraw
    out, per = [], cols * rows
    for s in range(0, len(models), per):
        batch = models[s:s + per]
        h = int(w * 0.42)
        sheet = Image.new("RGB", (cols * w, rows * (h + 22)), (24, 24, 24))
        d = ImageDraw.Draw(sheet)
        for i, m in enumerate(batch):
            im = Image.open(os.path.join(outdir, m["shot"])).convert("RGB")
            W, H = im.size
            cw, ch = int(W * 0.62), int(W * 0.62 * 0.42)
            im = im.crop(((W - cw) // 2, (H - ch) // 2, (W + cw) // 2, (H + ch) // 2))
            im = im.resize((w, h))
            x, y = (i % cols) * w, (i // cols) * (h + 22)
            sheet.paste(im, (x, y + 22))
            d.text((x + 4, y + 4), "%d %s" % (s + i, m["file"].split("::/")[-1])[:80],
                   fill=(255, 255, 255))
        name = "sheet_%02d.png" % (s // per)
        sheet.save(os.path.join(outdir, name))
        out.append(name)
    return out


def main():
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    args = sys.argv[1:]
    if not args:
        sys.exit(__doc__)
    names = vehicle_names() if args == ["--all"] else args
    mods = vehicles(names)
    d = ensure_tools_mod()
    open(os.path.join(d, "content", "smoke.lua"), "w", encoding="utf-8").write(
        SCRIPT % {"mods": ", ".join('"%s"' % m for m in mods), "settle": 90,
                  # camera: distance as a multiple of the model's length,
                  # angle and pitch as the game's camera data takes them
                  "dist": os.environ.get("SMOKE_DIST", "0.85"),
                  "angle": os.environ.get("SMOKE_ANGLE", "1.5708"),
                  "pitch": os.environ.get("SMOKE_PITCH", "0.18")})

    before = set(glob.glob(os.path.join(SHOTS, "*")))
    started = time.time()
    run = time.strftime("%Y%m%d_%H%M%S")
    outdir = os.path.join(LOGS, "smoke", run)
    os.makedirs(outdir, exist_ok=True)
    timeout = 120 + 6 * 40 * len(mods)
    code, killed, secs = game_run.run(["--script", "%s::/smoke.lua" % TOOLS_MOD],
                                      timeout=timeout,
                                      log=os.path.join(outdir, "stdout.txt"))
    print("game exit=%s killed=%s after %.0fs" % (code, killed, secs))
    shutil.copy2(GAME_LOG,
                 os.path.join(outdir, "game_log.txt"))
    models = []
    for l in open(os.path.join(outdir, "game_log.txt"), encoding="utf-8", errors="replace"):
        if "SMOKE_JSON " in l:
            try:
                models.append(json.loads(l.split("SMOKE_JSON ", 1)[1].strip()))
            except ValueError:
                pass
    if not models:
        sys.exit("no result - see %s" % os.path.join(outdir, "game_log.txt"))
    shots = sorted((f for f in glob.glob(os.path.join(SHOTS, "*"))
                    if f not in before and os.path.getmtime(f) >= started - 1),
                   key=os.path.getmtime)
    shot_models = [m for m in models if m.get("shot")]
    if len(shots) != len(shot_models):
        print("WARNING: %d screenshots for %d models - pairing by order anyway"
              % (len(shots), len(shot_models)))
    for i, (m, f) in enumerate(zip(shot_models, shots)):
        stem = re.sub(r"[^a-z0-9_.-]+", "_", m["file"].split("::/")[-1].lower())
        dst = os.path.join(outdir, "%03d_%s%s" % (i, stem.replace("/", "_"),
                                                   os.path.splitext(f)[1]))
        shutil.move(f, dst)
        m["shot"] = os.path.basename(dst)
    json.dump(models, open(os.path.join(outdir, "models.json"), "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)
    sheets = contact_sheets(outdir, [m for m in models if m.get("shot")])
    print("contact sheets: %s" % ", ".join(sheets))
    print("%d models, %d screenshots -> %s" % (len(models), len(shots), outdir))
    for m in models:
        flag = "" if m.get("name") else "   <- NO NAME"
        print("  %-55s %s%s" % (m["file"], m.get("name", ""), flag))


if __name__ == "__main__":
    main()
